# Generated by Django 6.0.4 on 2026-04-25 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient_inventorymovement_recipe_stockreservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='shift_opening_cash_gte_zero'), models.CheckConstraint(condition=models.Q(('closing_cash_expected__gte', 0)), name='shift_closing_cash_expected_gte_zero'), models.CheckConstraint(condition=models.Q(('closing_cash_actual__gte', 0)), name='shift_closing_cash_actual_gte_zero')],
            },
        ),
    ]
