# Generated by Django 6.0.4 on 2026-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='counter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
