# Generated by Django 6.0.4 on 2026-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shift_counter_name_shift_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('INVENTORY', 'Inventory'), ('SHIFT', 'Shift'), ('REPORT', 'Report')], max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_auditl_event_t_f36ba9_idx'), models.Index(fields=['reference_id', 'created_at'], name='core_auditl_referen_b12d4e_idx')],
            },
        ),
    ]
